version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/OrderDiscount"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/OverdueInvoices"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/targets"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
