name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: Build and test on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: Linux
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: |
            8.0.x
      - name: Build OrderDiscount
        run: dotnet build src/OrderDiscount --configuration Release
      - name: Tests OrderDiscount
        run: dotnet test src/OrderDiscount --configuration Release --no-build
      - name: Build OverdueInvoices
        run: dotnet build src/OverdueInvoices --configuration Release
      - name: Tests OverdueInvoices
        run: dotnet test src/OverdueInvoices --configuration Release --no-build
